# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ask < Formula
  desc "CLI package manager for AI agent skills"
  homepage "https://github.com/nextlevel-co/ask"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nextlevel-co/ask/releases/download/v0.1.0/ask_0.1.0_darwin_amd64.tar.gz"
      sha256 "b403e6d443a8d48f346a8f0f0ea0e3b613e4a13bd6ccbc6aeeba8ba0867db7e5"

      define_method(:install) do
        bin.install "ask"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nextlevel-co/ask/releases/download/v0.1.0/ask_0.1.0_darwin_arm64.tar.gz"
      sha256 "0d9f608b3c43d386662e38684acf74ebec4914512f7a982262de14dea5a3cc13"

      define_method(:install) do
        bin.install "ask"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nextlevel-co/ask/releases/download/v0.1.0/ask_0.1.0_linux_amd64.tar.gz"
      sha256 "d483e2deafcd6b88197098b8ac8bb4af720beb8e78d81d911f5c30c1c9a4baec"
      define_method(:install) do
        bin.install "ask"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nextlevel-co/ask/releases/download/v0.1.0/ask_0.1.0_linux_arm64.tar.gz"
      sha256 "11122558645982719943f8d5cc7b6415b013cafae3f7fe9cd6ed8df75cedbb43"
      define_method(:install) do
        bin.install "ask"
      end
    end
  end

  test do
    system "#{bin}/ask", "version"
  end
end
