# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ask < Formula
  desc "CLI package manager for AI agent skills"
  homepage "https://github.com/nextlevel-co/ask"
  version "0.1.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nextlevel-co/ask-releases/releases/download/v0.1.6/ask_0.1.6_darwin_amd64.tar.gz"
      sha256 "34573b628a31f76e501c31b41eea52e8f16d4d81f8eb153df36c97261a7836ed"

      define_method(:install) do
        bin.install "ask"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nextlevel-co/ask-releases/releases/download/v0.1.6/ask_0.1.6_darwin_arm64.tar.gz"
      sha256 "ccb869588bc0072025d8601fc48aa22f213683fb7f3325cd1e2bd89a2513644b"

      define_method(:install) do
        bin.install "ask"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nextlevel-co/ask-releases/releases/download/v0.1.6/ask_0.1.6_linux_amd64.tar.gz"
      sha256 "6b5600a02be65532f73bfa02d5da8fca8ff7d72ccd32e577c5dc1c8d49f1e961"
      define_method(:install) do
        bin.install "ask"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nextlevel-co/ask-releases/releases/download/v0.1.6/ask_0.1.6_linux_arm64.tar.gz"
      sha256 "4ebd9dfb0d1cc27597754c7d85815ca5702b4f6820da36376a0686f282b1ac1a"
      define_method(:install) do
        bin.install "ask"
      end
    end
  end

  test do
    system "#{bin}/ask", "version"
  end
end
